AWSTemplateFormatVersion: 2010-09-09
Resources: 
  DevEC2Instance: 
    Type: 'AWS::EC2::Instance'
    Properties: 
      ImageId: ami-026669ec456129a70
      InstanceType: t2.micro
      KeyName: cfn-key-2
