AWSTemplateFormatVersion: '2010-09-09'
Description: VPC nested stack template

Parameters:
  VpcBlock:
    Type: String
    Default: 10.0.0.0/16
    Description: VPC CIDR Range

  Subnet01Block:
    Type: String  
    Default: 10.0.1.0/24 
    Description: CidrBlock for Subnet 01 within the VPC. 

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Lable:
          default: Dev VPC network configration
          Parameters:
            - VpcBlock
            - Subnet01Block
    ParameterLabels:
      VpcBlock: 
        default: VPC CIDR Range selection               

Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcBlock 
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-myVPC"
  
  Subnet01:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: !Ref Subnet01Block 
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-Subnet01"         
      AvailabilityZone:
        Fn::Select:
        - '0'
        - Fn::GetAZs:
            Ref: AWS::Region 

  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MyVPC
      Tags:
        - Key: Name
          Value: Public Subnets
        - Key: Network
          Value: Public 

  Subnet01RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref Subnet01
      RouteTableId: !Ref RouteTable

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref MyVPC 

  Route:
    DependsOn: VPCGatewayAttachment 
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway


Outputs:
  SubnetId:
    Description: Subnet01 Id
    Value: !Ref Subnet01

  VPCId:
    Description: VPC ID
    Value: !Ref MyVPC          