AWSTemplateFormatVersion: 2010-09-09
Description: CFN Init Demo

Parameter:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName



Resources:
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
    GroupDescription: My SG with port 22, 8080 and 80 inbound
    SecurityGroupIngress:
    - IpProtocol: tcp
      FromPort: '22'
      ToPort: '22'
      Cidr: 0.0.0.0/0
    - IpProtocol: tcp
      FromPort: '8080'
      ToPort: '8080'
      CidrIp: 0.0.0.0/0

  MyVMInstances:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-08f63db601b82ff5f
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      SecurityGroups:
      - !Ref MySecurityGroup
